# Generated by Django 5.2 on 2025-04-17 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100, unique=True)),
                ('DisplayName', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('XP', models.IntegerField(default=0)),
                ('Level', models.IntegerField(default=1)),
                ('Reputation', models.IntegerField(default=0)),
                ('Verified', models.BooleanField(default=False)),
                ('Developer', models.BooleanField(default=False)),
                ('CanReceiveInvites', models.BooleanField(default=False)),
                ('ProfileImage', models.ImageField(blank=True, default='profile_images/DefaultProfileImage.png', null=True, upload_to='profile_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Logins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platform', models.IntegerField(choices=[(0, 'Steam'), (1, 'Oculus'), (2, 'PlayStation 4'), (5, 'Microsoft')], default=0)),
                ('PlatformId', models.CharField(max_length=100)),
                ('LastLoginDateTime', models.DateTimeField()),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
