# Generated by Django 5.2 on 2025-04-18 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsOnline', models.BooleanField(default=False)),
                ('GameSessionId', models.CharField(blank=True, max_length=100, null=True)),
                ('AppVersion', models.CharField(blank=True, max_length=100, null=True)),
                ('Activity', models.CharField(blank=True, max_length=100, null=True)),
                ('Private', models.BooleanField(default=False)),
                ('AvailableSpace', models.IntegerField(default=0)),
                ('GameInProgress', models.BooleanField(default=False)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
