# Generated by Django 5.2 on 2025-04-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerpresence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OutfitSelections', models.CharField(blank=True, max_length=1000, null=True)),
                ('HairColor', models.CharField(blank=True, max_length=1000, null=True)),
                ('SkinColor', models.CharField(blank=True, max_length=1000, null=True)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SentTime', models.DateTimeField(auto_now_add=True)),
                ('Type', models.IntegerField(choices=[(0, 'Game Invite'), (1, 'Game Invite Declined'), (2, 'Game Join Failed'), (3, 'Party Activity Switch'), (4, 'Friend Invite'), (5, 'Vote To Kick'), (10, 'Request Game Invite'), (11, 'Request Game Invite Declined'), (20, 'Friend Status Online'), (30, 'Text Message'), (40, 'Friend Request Accepted')])),
                ('Data', models.CharField(max_length=1000)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.player')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.player')),
            ],
        ),
    ]
