# Generated by Django 5.2 on 2025-04-18 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Activity', models.IntegerField(choices=[(-1, 'Invalid'), (1000, 'Dorm Room'), (2000, 'Rec Center'), (3000, 'Charades'), (4000, 'Disc Golf'), (5000, 'Dodgeball'), (6000, 'The Lounge'), (7000, 'Paddleball'), (8000, 'Paintball'), (9000, 'Quest'), (10000, 'Soccer'), (11000, 'Art Testing'), (12000, 'Performance Hall'), (13000, 'Room Calibration')], default=-1)),
                ('ActivityLevel', models.IntegerField(choices=[(-1, 'Invalid'), (0, 'Any Level'), (1, 'Dorm Room'), (2, 'Rec Center'), (3, 'Charades'), (4, 'Lake'), (5, 'Propulsion'), (6, 'Dodgeball'), (7, 'The Lounge'), (8, 'Paddleball'), (9, 'River'), (10, 'Homestead'), (11, 'Quarry'), (12, 'Clear Cut'), (13, 'Spillway'), (14, 'Quest For The Golden Trophy'), (15, 'The Rise Of Jumbotron'), (16, 'Curse Of The Crimson Cauldron'), (17, 'Soccer'), (18, 'Art Testing'), (19, 'Art Testing Perf'), (20, 'Dorm Photo Studio'), (21, 'Performance Hall'), (22, 'Room Calibration')], default=-1)),
                ('PosterImage', models.ImageField(upload_to='event_posters/')),
                ('GameSessionId', models.CharField(max_length=100)),
                ('MaxPlayers', models.IntegerField(default=0)),
                ('CreatorPlayerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='core.player')),
            ],
        ),
    ]
