# Generated by Django 5.2 on 2025-04-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='CreatorPlayerId',
            new_name='CreatorPlayer',
        ),
    ]
