# Generated by Django 5.2 on 2025-04-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_dynamicposter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FriendlyName', models.CharField(max_length=100)),
                ('PrefabName', models.CharField(max_length=100)),
                ('ModificationGuid', models.CharField(max_length=100)),
                ('UnlockedLevel', models.IntegerField(default=0)),
            ],
        ),
    ]
