# Generated by Django 5.2 on 2025-04-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_giftdrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='player_images/')),
                ('GameSessionId', models.CharField(max_length=100)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
