# Generated by Django 5.2 on 2025-04-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_playerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(upload_to='video/')),
                ('PlayButtonImage', models.ImageField(upload_to='video_image/')),
                ('Volume', models.FloatField(default=0.1)),
                ('PitchVariation', models.FloatField(default=0.0)),
                ('PitchShift', models.FloatField(default=0.0)),
            ],
        ),
    ]
