# Generated by Django 5.2 on 2025-04-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_howtovideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtovideo',
            name='PlayButtonImage',
            field=models.ImageField(blank=True, null=True, upload_to='video_image/'),
        ),
    ]
