# Generated by Django 5.2 on 2025-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='radio',
            name='AudioType',
            field=models.IntegerField(choices=[(0, 'Unknown'), (1, 'Acc'), (2, 'Aiff'), (10, 'It'), (12, 'Mod'), (13, 'Mpeg'), (14, 'Oggvorbis'), (17, 'S3M'), (20, 'Wav'), (21, 'Xm'), (22, 'Xma'), (23, 'Vag'), (24, 'Audioqueue')], default=14),
        ),
    ]
