# Generated by Django 5.2 on 2025-04-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_radio_audiotype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logins',
            new_name='Login',
        ),
        migrations.AlterField(
            model_name='event',
            name='Description',
            field=models.TextField(max_length=3000),
        ),
    ]
