# Generated by Django 5.2 on 2025-04-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_logins_login_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FriendlyName', models.CharField(max_length=100)),
                ('outfitItem', models.CharField(max_length=100)),
                ('colorSwatch', models.CharField(blank=True, max_length=100, null=True)),
                ('mask', models.CharField(blank=True, max_length=100, null=True)),
                ('decal', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
