# Generated by Django 5.2 on 2025-04-21 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_outfititem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfititem',
            old_name='FriendlyName',
            new_name='friendlyName',
        ),
    ]
