# Generated by Django 5.2 on 2025-04-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_friendlyname_outfititem_friendlyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharadesWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EN_US', models.CharField(max_length=100)),
                ('Difficulty', models.IntegerField(choices=[(0, 'Easy'), (1, 'Hard')], default=0)),
            ],
        ),
    ]
