# Generated by Django 5.2 on 2025-04-22 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_charadeswords'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelProgressionMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField(default=0)),
                ('RequiredXp', models.IntegerField(default=0)),
            ],
        ),
    ]
