# Generated by Django 5.2 on 2025-04-22 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_levelprogressionmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartAt', models.DateTimeField(auto_now_add=True)),
                ('EndAt', models.DateTimeField()),
                ('Reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
