# Generated by Django 5.2 on 2025-04-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ban'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='ReportCategory',
            field=models.IntegerField(choices=[(-1, 'Moderator'), (0, 'Unknown'), (1, 'Deprecated Microphoneabuse'), (2, 'Harassment'), (3, 'Cheating'), (4, 'Deprecated Immaturebehavior'), (5, 'Deprecated Afk'), (6, 'Misc'), (7, 'Underage')], default=0),
        ),
    ]
