# Generated by Django 5.2 on 2025-04-22 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_outfititem_outfititem_outfititem_prefab'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftdrop',
            name='FriendlyName',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftdrop',
            name='OutfitItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.outfititem'),
        ),
    ]
