# Generated by Django 5.2 on 2025-04-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_giftdrop_friendlyname_giftdrop_outfititem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartAt', models.DateTimeField()),
                ('EndAt', models.DateTimeField()),
                ('Challenges', models.ManyToManyField(blank=True, to='core.challenge')),
                ('GiftsDrops', models.ManyToManyField(blank=True, to='core.giftdrop')),
            ],
        ),
    ]
