# Generated by Django 5.2 on 2025-04-24 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_challenge_challengemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SentAt', models.DateTimeField(auto_now_add=True)),
                ('Message', models.CharField(max_length=1000)),
                ('Opened', models.BooleanField(default=False)),
                ('GiftDrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giftdrop')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
        migrations.CreateModel(
            name='MyGiGiftDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddedAt', models.DateTimeField(auto_now_add=True)),
                ('GiftDrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.giftdrop')),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
