# Generated by Django 5.2 on 2025-04-24 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_gift_mygigiftdrop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Used', models.BooleanField(default=False)),
                ('Player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
        ),
    ]
