# Generated by Django 5.2 on 2025-04-27 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_playeremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RelationshipType', models.IntegerField(choices=[(-1, 'None '), (0, 'Friendrequestsent'), (1, 'Friendrequestreceived'), (2, 'Friend')], default=-1)),
                ('Player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player', to='core.player')),
                ('Player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlayerShip', to='core.player')),
            ],
        ),
    ]
