# Generated by Django 5.2 on 2025-04-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='RelationshipType',
            field=models.IntegerField(choices=[(0, 'None '), (1, 'Friendrequestsent'), (2, 'Friendrequestreceived'), (3, 'Friend')], default=0),
        ),
    ]
