# Generated by Django 5.2 on 2025-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_relationship_relationshiptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='RelationshipType',
            field=models.IntegerField(choices=[(0, 'None '), (1, 'Friendrequestsent'), (2, 'Friendrequestreceived'), (3, 'Friend'), (4, 'Blockedlocal'), (5, 'Blockedremote'), (6, 'Blockedmutual')], default=0),
        ),
    ]
