# Generated by Django 5.2 on 2025-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_relationship_relationshiptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='Ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='Mute',
            field=models.BooleanField(default=False),
        ),
    ]
