# Generated by Django 5.2 on 2025-04-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_relationship_ignore_relationship_mute'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Password',
            field=models.CharField(blank=True, default=None, max_length=4000, null=True),
        ),
    ]
