from django.urls import include, path
from core import apiviews

urlpatterns = [
    path('test', apiviews.test),
    path('api/versioncheck/v3', apiviews.versioncheck),
    path('api/config/v2', apiviews.config),
    path('api/howToVideo/v2/random', apiviews.HowToVideoConfig),
    path('api/radio/v2/list', apiviews.raido),
    path('api/platformlogin/v1/profiles', apiviews.platformlogins),
    path('api/platformlogin/v5', apiviews.platformlogin),
    path('api/players/v1/<int:playerId2>', apiviews.playerById),
    path('api/messages/v2/get', apiviews.messages),
    path('api/relationships/v2/get', apiviews.relationships),
    path('api/avatar/v2', apiviews.avatar),
    path('api/avatar/v2/set', apiviews.avatarset),
    path('api/settings/v2/', apiviews.settings),
    path('api/settings/v2/<action>', apiviews.settingsset),
    path('api/avatar/v3/items', apiviews.UnlockedAvatarItems),
    path('api/equipment/v1/getUnlocked', apiviews.UnlockedEquipments),
    path('api/avatar/v2/gifts', apiviews.gifts),
    path('api/events/v2/list', apiviews.events),
    path('api/activities/charades/v1/words', apiviews.charadesWords),
    path('api/players/v1/list', apiviews.getAllPlayers),
    path('api/avatar/v2/gifts/generate', apiviews.giftsGenerate),
    path('api/messages/v2/send', apiviews.messagessend),
    path('api/messages/v2/delete', apiviews.messagesdelete),
    path('api/players/v1/listByPlatformId', apiviews.listByPlatformId),
    path('api/images/v1/named', apiviews.imgnamedata),
    path('api/gamesessions/v1/isfull/<gamesessionId>', apiviews.gamesessionsIsFull),
    path('api/images/v1/uploadtransient', apiviews.uploadtransient),
    path('api/players/v2/search', apiviews.searchPlayer),
    path('api/images/v2/profile', apiviews.updatePlayerPfp),
    path('api/players/v2/displayname', apiviews.updateDisplayname),
    path('api/players/v1/createProfile', apiviews.createProfile),
    path('api/players/v1/blockduration', apiviews.blockduration),
    path('api/PlayerReporting/v1/create', apiviews.report),
    path('api/avatar/v2/gifts/consume/', apiviews.giftconsume),
    path('api/players/v2/verify', apiviews.email),
    path('api/relationships/v2/sendfriendrequest', apiviews.sendfriendrequest),
    path('api/relationships/v2/acceptfriendrequest', apiviews.acceptfriendrequest),
    path('api/relationships/v2/removefriend', apiviews.removefriend),
    path('api/messages/v1/sendMultiple', apiviews.sendMultiple),
    path('api/public/player/<int:playerId>', apiviews.pubPlayerById),
    path('api/public/player', apiviews.pubPlayerByUsername),
    path('api/email/player/UpdateAccount', apiviews.updateUsernamePassword),
    path('api/challenge/v1/getCurrent', apiviews.challenge),

]